security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$cIWoGahLCuxIL5a7eFYx.el1NMbKmCDsQP9bBMXyVZVj6qoDNpZnG
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin/
            http_basic: true
            provider: in_memory
    access_control:
        - { path: ^/api/, roles: ROLE_API }
        - { path: ^/admin/, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User:
           algorithm: bcrypt
           cost: 12
